apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-1
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi