apiVersion: v1
kind: Secret
metadata:
  name: registry-key
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0MTJoMWFjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoidDEyaDFhY3IiLCJwYXNzd29yZCI6Inh5ZzY1dytLQ0RGcTU9TVl6cHB4RSs5U2lib3VtWnpmIiwiZW1haWwiOiJub3RAdXNlZC5jb20iLCJhdXRoIjoiZERFeWFERmhZM0k2ZUhsbk5qVjNLMHREUkVaeE5UMU5XWHB3Y0hoRkt6bFRhV0p2ZFcxYWVtWT0ifX19
type: kubernetes.io/dockerconfigjson
